import type { Benefit, BenefitOperativ, BenefitStrategisch, BenefitRisiko } from "./types";

// --- Operativ (9 benefits) ---

const BENEFITS_OPERATIV = [
  {
    id: "liefer-umfang",
    titel: "Liefer-Umfang vervielfacht sich",
    kachelTyp: "operativ",
    kategorie: "tempo",
    defaultPrio: 1,
    plateauLabel: "3x mehr Output",
    effektGroesse: 0.67,
    anlaufzeitIterationen: 12,
    kurvenForm: "sigmoid",
    phaseVoraussetzung: 2,
    painPoints: ["shipping-zu-langsam"],
    kpiBetroffen: ["feature_anteil", "kosten_pro_feature"],
    erfahrungsBasis: "Dokumentiert. Pilotprojekt + Eigenpraxis.",
  },
  {
    id: "routine-automatisiert",
    titel: "Routine-Aufgaben werden automatisiert",
    kachelTyp: "operativ",
    kategorie: "tempo",
    defaultPrio: 2,
    plateauLabel: "-60% Routine-Aufwand",
    effektGroesse: 0.60,
    anlaufzeitIterationen: 8,
    kurvenForm: "sigmoid",
    phaseVoraussetzung: 2,
    painPoints: ["shipping-zu-langsam", "bug-last"],
    kpiBetroffen: ["feature_anteil"],
    erfahrungsBasis: "Eigenpraxis. Migrationen, CRUD, Boilerplate.",
  },
  {
    id: "kosten-pro-feature",
    titel: "Kosten pro Feature sinken auf ein Drittel",
    kachelTyp: "operativ",
    kategorie: "tempo",
    defaultPrio: 1,
    plateauLabel: "1/3 Kosten pro Feature",
    effektGroesse: 0.67,
    anlaufzeitIterationen: 12,
    kurvenForm: "sigmoid",
    phaseVoraussetzung: 2,
    painPoints: ["shipping-zu-langsam"],
    kpiBetroffen: ["kosten_pro_feature"],
    erfahrungsBasis: "Direkt gekoppelt an Liefer-Umfang.",
  },
  {
    id: "bug-pre-trial",
    titel: "Bugs werden vom AI-Agent vorbearbeitet",
    kachelTyp: "operativ",
    kategorie: "qualitaet",
    defaultPrio: 1,
    plateauLabel: "-72% Bug-Aufwand",
    effektGroesse: 0.72,
    anlaufzeitIterationen: 8,
    kurvenForm: "sigmoid",
    phaseVoraussetzung: 2,
    painPoints: ["bug-last"],
    kpiBetroffen: ["bug_h_pro_bug", "bug_anteil_am_aufwand", "feature_anteil"],
    erfahrungsBasis: "Pilotprojekt + Eigenpraxis.",
  },
  {
    id: "tests-sicherheitsnetz",
    titel: "Tests werden zum echten Sicherheitsnetz",
    kachelTyp: "operativ",
    kategorie: "qualitaet",
    defaultPrio: 2,
    plateauLabel: "+40pp Coverage",
    effektGroesse: 0.60,
    anlaufzeitIterationen: 16,
    kurvenForm: "linear_ramp",
    phaseVoraussetzung: 2,
    painPoints: ["bug-last", "releases-stress"],
    kpiBetroffen: ["test_coverage", "production_incidents"],
    erfahrungsBasis: "Eigenpraxis. Stetiger Aufbau.",
  },
  {
    id: "ai-reviewer-pr",
    titel: "AI als zweite Lese-Ebene auf jedem PR",
    kachelTyp: "operativ",
    kategorie: "qualitaet",
    defaultPrio: 2,
    plateauLabel: "-30% Review-Zeit",
    effektGroesse: 0.30,
    anlaufzeitIterationen: 4,
    kurvenForm: "linear_ramp",
    phaseVoraussetzung: 1,
    painPoints: ["bug-last"],
    kpiBetroffen: ["review_h_pro_pr", "lead_time"],
    erfahrungsBasis: "Eigenpraxis. Stabil über mehrere Projekte.",
  },
  {
    id: "performance-messbar",
    titel: "Performance wird messbar",
    kachelTyp: "operativ",
    kategorie: "qualitaet",
    defaultPrio: 3,
    plateauLabel: "Bottlenecks automatisch erkannt",
    effektGroesse: 0.40,
    anlaufzeitIterationen: 6,
    kurvenForm: "treppen",
    treppenStufen: [3, 6],
    phaseVoraussetzung: 2,
    painPoints: ["shipping-zu-langsam"],
    kpiBetroffen: ["production_incidents"],
    erfahrungsBasis: "Eigenpraxis. Profiling + Perf-Tests.",
  },
  {
    id: "onboarding-reibungsarm",
    titel: "Onboarding wird reibungsarm",
    kachelTyp: "operativ",
    kategorie: "wissen",
    defaultPrio: 2,
    plateauLabel: "-60% Onboarding-Tage",
    effektGroesse: 0.60,
    anlaufzeitIterationen: 12,
    kurvenForm: "linear_ramp",
    phaseVoraussetzung: 2,
    painPoints: ["onboarding-langsam"],
    kpiBetroffen: ["onboarding_tage"],
    erfahrungsBasis: "Erfahrungsschätzung. Spec-Driven-Repo + AI als Erklärer.",
  },
  {
    id: "notfall-bereitschaft",
    titel: "Notfall-Bereitschaft sinkt",
    kachelTyp: "operativ",
    kategorie: "qualitaet",
    defaultPrio: 2,
    plateauLabel: "-50% Hotfixes/Monat",
    effektGroesse: 0.50,
    anlaufzeitIterationen: 12,
    kurvenForm: "sigmoid",
    phaseVoraussetzung: 2,
    painPoints: ["bug-last", "releases-stress"],
    kpiBetroffen: ["production_incidents"],
    erfahrungsBasis: "Erfahrungsschätzung. Test-Netz + Quality-Gates.",
  },
] as const satisfies readonly BenefitOperativ[];

// --- Strategisch (7 benefits) ---

const BENEFITS_STRATEGISCH = [
  {
    id: "ideen-ausprobieren",
    titel: "Ideen können schnell ausprobiert werden",
    kachelTyp: "strategisch",
    kategorie: "tempo",
    defaultPrio: 2,
    proxyVorher: "2 Prototypen pro Quartal",
    proxyNachher: "6 Prototypen pro Quartal",
    anlaufzeitIterationen: 4,
    kurvenForm: "linear_ramp",
    phaseVoraussetzung: 1,
    painPoints: ["shipping-zu-langsam"],
    erfahrungsBasis: "Eigenpraxis. Spec-Driven + AI-Code-Generation.",
  },
  {
    id: "releases-planbar",
    titel: "Releases werden planbar und stressfrei",
    kachelTyp: "strategisch",
    kategorie: "tempo",
    defaultPrio: 2,
    proxyVorher: "Release alle 6 Wochen, manuell",
    proxyNachher: "Release alle 2 Wochen, automatisiert",
    anlaufzeitIterationen: 6,
    kurvenForm: "treppen",
    treppenStufen: [2, 4, 6],
    phaseVoraussetzung: 1,
    painPoints: ["releases-stress"],
    erfahrungsBasis: "Eigenpraxis. CI-Pipeline, Rollback, Quality-Gates.",
  },
  {
    id: "spec-driven-rework",
    titel: "Spec-Driven-Workflow reduziert Missverständnisse",
    kachelTyp: "strategisch",
    kategorie: "produkt",
    defaultPrio: 3,
    proxyVorher: "3-4 Rework-Zyklen pro Feature",
    proxyNachher: "1-2 Rework-Zyklen pro Feature",
    anlaufzeitIterationen: 8,
    kurvenForm: "linear_ramp",
    phaseVoraussetzung: 3,
    painPoints: ["shipping-zu-langsam"],
    erfahrungsBasis: "Eigenpraxis. Specs vor Code.",
  },
  {
    id: "roadmap-planbar",
    titel: "Roadmap wird transparent und planbar",
    kachelTyp: "strategisch",
    kategorie: "produkt",
    defaultPrio: 3,
    proxyVorher: "40-60% Roadmap-Treffquote",
    proxyNachher: "80% Roadmap-Treffquote",
    anlaufzeitIterationen: 12,
    kurvenForm: "linear_ramp",
    phaseVoraussetzung: 3,
    painPoints: ["shipping-zu-langsam", "releases-stress"],
    erfahrungsBasis: "Erfahrungsschätzung. Spec-Driven + Velocity-Messung.",
  },
  {
    id: "feedback-schneller",
    titel: "Kunden-Feedback wird schneller verarbeitet",
    kachelTyp: "strategisch",
    kategorie: "produkt",
    defaultPrio: 3,
    proxyVorher: "2 Monate von Idee bis Production",
    proxyNachher: "2 Wochen von Idee bis Production",
    anlaufzeitIterationen: 8,
    kurvenForm: "sigmoid",
    phaseVoraussetzung: 3,
    painPoints: ["shipping-zu-langsam"],
    erfahrungsBasis: "Eigenpraxis. Lead-Time-Reduktion.",
  },
  {
    id: "plattform-differenziator",
    titel: "Plattform wird differenziator-fähig",
    kachelTyp: "strategisch",
    kategorie: "produkt",
    defaultPrio: 4,
    proxyVorher: "0 AI-Features im Produkt",
    proxyNachher: "3 AI-Features im nächsten Release",
    anlaufzeitIterationen: 16,
    kurvenForm: "treppen",
    treppenStufen: [8, 12, 16],
    phaseVoraussetzung: 4,
    painPoints: ["sales-bruecke"],
    erfahrungsBasis: "Erfahrungsschätzung. Hängt von Produkt-Domäne ab.",
  },
  {
    id: "sales-bruecke-entlastet",
    titel: "Sales-/Marketing-Brücke wird entlastet",
    kachelTyp: "strategisch",
    kategorie: "produkt",
    defaultPrio: 4,
    proxyVorher: "0h/Woche GF-Zeit frei für Sales",
    proxyNachher: "8h/Woche GF-Zeit frei für Sales",
    anlaufzeitIterationen: 20,
    kurvenForm: "linear_ramp",
    phaseVoraussetzung: 5,
    painPoints: ["sales-bruecke"],
    erfahrungsBasis: "Erfahrungsschätzung. Abhängig von GF-Involvement.",
  },
] as const satisfies readonly BenefitStrategisch[];

// --- Risiko (15 benefits) ---

const BENEFITS_RISIKO = [
  {
    id: "refactoring-angstfrei",
    titel: "Refaktorierungen werden angstfrei",
    kachelTyp: "risiko",
    kategorie: "qualitaet",
    defaultPrio: 3,
    vorher: "Angst vor Umbau, Tech-Debt wächst",
    nachher: "Test-Netz fängt alles, Umbau ist Routine",
    anlaufzeitIterationen: 16,
    kurvenForm: "linear_ramp",
    phaseVoraussetzung: 2,
    painPoints: ["releases-stress"],
    erfahrungsBasis: "Erfahrungsschätzung.",
  },
  {
    id: "sicherheit-substrat",
    titel: "Sicherheit ist Substrat, nicht Sonderprojekt",
    kachelTyp: "risiko",
    kategorie: "qualitaet",
    defaultPrio: 3,
    vorher: "Security als Sonderprojekt alle 6 Monate",
    nachher: "Audit-Logs, Secrets, CVEs laufen automatisch mit",
    anlaufzeitIterationen: 8,
    kurvenForm: "treppen",
    treppenStufen: [3, 5, 8],
    phaseVoraussetzung: 2,
    painPoints: ["compliance-audits"],
    erfahrungsBasis: "Branchenerfahrung.",
  },
  {
    id: "compliance-ohne-sonderaktion",
    titel: "Compliance-fähig ohne Sonderaktion",
    kachelTyp: "risiko",
    kategorie: "qualitaet",
    defaultPrio: 3,
    vorher: "Audit = Sonderprojekt, 40h/Quartal",
    nachher: "Audit = Routine-Übung, läuft mit",
    anlaufzeitIterationen: 6,
    kurvenForm: "treppen",
    treppenStufen: [2, 4, 6],
    phaseVoraussetzung: 2,
    painPoints: ["compliance-audits"],
    erfahrungsBasis: "Branchenerfahrung.",
  },
  {
    id: "architektur-dokumentiert",
    titel: "Architektur wird dokumentiert",
    kachelTyp: "risiko",
    kategorie: "wissen",
    defaultPrio: 3,
    vorher: "Architektur im Kopf des Seniors",
    nachher: "ADR-Einträge im Repo, Trade-offs nachvollziehbar",
    anlaufzeitIterationen: 8,
    kurvenForm: "linear_ramp",
    phaseVoraussetzung: 2,
    painPoints: ["bus-faktor"],
    erfahrungsBasis: "Eigenpraxis.",
  },
  {
    id: "domain-wissen",
    titel: "Domain-Wissen wird zugänglich",
    kachelTyp: "risiko",
    kategorie: "wissen",
    defaultPrio: 3,
    vorher: "Frag den einen der es weiss",
    nachher: "Lies Glossar im Repo",
    anlaufzeitIterationen: 12,
    kurvenForm: "linear_ramp",
    phaseVoraussetzung: 3,
    painPoints: ["bus-faktor", "onboarding-langsam"],
    erfahrungsBasis: "Erfahrungsschätzung.",
  },
  {
    id: "bus-faktor-aufloesung",
    titel: "Bus-Faktor löst sich auf",
    kachelTyp: "risiko",
    kategorie: "wissen",
    defaultPrio: 2,
    vorher: "1 Person hält das Wissen",
    nachher: "Wissen auf Team und KI verteilt",
    anlaufzeitIterationen: 24,
    kurvenForm: "linear_ramp",
    phaseVoraussetzung: 3,
    painPoints: ["bus-faktor"],
    erfahrungsBasis: "Erfahrungsschätzung.",
  },
  {
    id: "ai-mentor",
    titel: "AI als Mentor für Junior-Entwickler",
    kachelTyp: "risiko",
    kategorie: "wissen",
    defaultPrio: 3,
    vorher: "Senior erklärt, Senior-Zeit blockiert",
    nachher: "AI erklärt, Senior ist frei für Architektur",
    anlaufzeitIterationen: 8,
    kurvenForm: "linear_ramp",
    phaseVoraussetzung: 2,
    painPoints: ["onboarding-langsam"],
    erfahrungsBasis: "Eigenpraxis.",
  },
  {
    id: "cross-stack",
    titel: "Cross-Stack-Verständnis wächst",
    kachelTyp: "risiko",
    kategorie: "wissen",
    defaultPrio: 4,
    vorher: "Nur Frontend oder nur Backend",
    nachher: "Liest und versteht den anderen Stack mit AI-Hilfe",
    anlaufzeitIterationen: 20,
    kurvenForm: "linear_ramp",
    phaseVoraussetzung: 4,
    painPoints: ["bus-faktor", "onboarding-langsam"],
    erfahrungsBasis: "Erfahrungsschätzung.",
  },
  {
    id: "eigenstaendige-ai-skill",
    titel: "Eigenständige AI-Skill im Team",
    kachelTyp: "risiko",
    kategorie: "wissen",
    defaultPrio: 4,
    vorher: "PD-abhängig für AI-Workflows",
    nachher: "Team nutzt AI-Tools autonom, Faktor 2-3x Eigenleistung realistisch",
    anlaufzeitIterationen: 24,
    kurvenForm: "linear_ramp",
    phaseVoraussetzung: 4,
    painPoints: ["bus-faktor"],
    erfahrungsBasis: "Kalkulator zeigt konservativ 1.5x, reale Teams 2-3x.",
  },
  {
    id: "tech-debt-sichtbar",
    titel: "Tech-Debt sichtbar gemacht",
    kachelTyp: "risiko",
    kategorie: "produkt",
    defaultPrio: 3,
    vorher: "Überraschungen bei jedem Sprint",
    nachher: "Kontinuierliche Diagnose, priorisiert",
    anlaufzeitIterationen: 4,
    kurvenForm: "treppen",
    treppenStufen: [2, 4],
    phaseVoraussetzung: 2,
    painPoints: ["releases-stress"],
    erfahrungsBasis: "Eigenpraxis.",
  },
  {
    id: "cs-verstaendnis",
    titel: "Customer Success versteht Plattform tiefer",
    kachelTyp: "risiko",
    kategorie: "produkt",
    defaultPrio: 4,
    vorher: "CS fragt Dev bei jeder Plattform-Frage",
    nachher: "CS findet Antworten selbst via Doku + AI",
    anlaufzeitIterationen: 16,
    kurvenForm: "linear_ramp",
    phaseVoraussetzung: 4,
    painPoints: ["sales-bruecke"],
    erfahrungsBasis: "Erfahrungsschätzung.",
  },
  {
    id: "migrations-risiken",
    titel: "Migrations-Risiken sinken",
    kachelTyp: "risiko",
    kategorie: "produkt",
    defaultPrio: 3,
    vorher: "Daumen drücken bei Schema-Migration",
    nachher: "Tests + Schema-Tracking + Rollback",
    anlaufzeitIterationen: 8,
    kurvenForm: "treppen",
    treppenStufen: [4, 8],
    phaseVoraussetzung: 2,
    painPoints: ["releases-stress"],
    erfahrungsBasis: "Eigenpraxis.",
  },
  {
    id: "wissen-verteilt",
    titel: "Erste-Person-Wissen wird Team-Wissen",
    kachelTyp: "risiko",
    kategorie: "strategisch",
    defaultPrio: 4,
    vorher: "Einzel-Köpfe, Pairing informell",
    nachher: "Spec-Driven verteilt Know-how systematisch",
    anlaufzeitIterationen: 24,
    kurvenForm: "linear_ramp",
    phaseVoraussetzung: 3,
    painPoints: ["bus-faktor"],
    erfahrungsBasis: "Erfahrungsschätzung.",
  },
  {
    id: "plattform-selbstwartend",
    titel: "Plattform wird selbstwartend",
    kachelTyp: "risiko",
    kategorie: "strategisch",
    defaultPrio: 5,
    vorher: "PD nötig für Tagesgeschäft",
    nachher: "Team trägt Plattform eigenständig",
    anlaufzeitIterationen: 36,
    kurvenForm: "linear_ramp",
    phaseVoraussetzung: 7,
    painPoints: ["bus-faktor"],
    erfahrungsBasis: "Erfahrungsschätzung.",
  },
  {
    id: "investorengeschichte",
    titel: "Investorengeschichte wird erzählbar",
    kachelTyp: "risiko",
    kategorie: "strategisch",
    defaultPrio: 5,
    vorher: "Kein Pitch-Deck-fähiges Plattform-Argument",
    nachher: "AI-First, dokumentiert, messbar, investierbar",
    anlaufzeitIterationen: 36,
    kurvenForm: "treppen",
    treppenStufen: [20, 28, 36],
    phaseVoraussetzung: 8,
    painPoints: ["sales-bruecke"],
    erfahrungsBasis: "Erfahrungsschätzung.",
  },
] as const satisfies readonly BenefitRisiko[];

export const BENEFITS: readonly Benefit[] = [
  ...BENEFITS_OPERATIV,
  ...BENEFITS_STRATEGISCH,
  ...BENEFITS_RISIKO,
];

// Predefined compounding pairs (for CompoundingLines component)
export const COMPOUNDING_PAIRS: readonly { from: string; to: string; label: string }[] = [
  { from: "bug-pre-trial", to: "liefer-umfang", label: "weniger Bugs = mehr Feature-Zeit" },
  { from: "tests-sicherheitsnetz", to: "refactoring-angstfrei", label: "Tests = angstfreier Umbau" },
  { from: "architektur-dokumentiert", to: "onboarding-reibungsarm", label: "Doku = schnelleres Onboarding" },
  { from: "spec-driven-rework", to: "roadmap-planbar", label: "Specs = planbare Roadmap" },
];
